In [2]:
import numpy as np

# 1. Create a null vector of size 10 but the fifth value which is 1

vector = np.zeros(10)
vector[5]=1
print(vector)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [3]:
# 2. Create a vector with values ranging from 10 to 49.

arr = np.arange(10,50)
print("Values Ranging from 10 to 49" ,arr)

Values Ranging from 10 to 49 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [4]:
# 3. Create a 3x3 matrix with values ranging from 0 to 8

matrix = np.arange(9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [5]:
# 4. Find indices of non-zero elements from [1,2,0,0,4,0]

elements = np.array([1,2,0,0,47,0])
result = np.where(elements == 0)[0]
print("Indices of non-zero Elements are ",result)

Indices of non-zero Elements are  [2 3 5]


In [6]:
# 5. Create a 10x10 array with random values and find the minimum and maximum values.

arr = np.random.random([10,10])
values = arr.min(), arr.max()
print("Min Value and Max values = ",values)

Min Value and Max values =  (0.0008644902120119591, 0.9886650116661946)


In [7]:
# 6. Create a random vector of size 30 and find the mean value.

vector = np.random.random(30)
result = vector.mean()
print("Mean Value = ",result)

Mean Value =  0.4922985535032726
