In [17]:
import numpy as np

# 1. Create a null vector of size 10 but the fifth value which is 1

vector = np.zeros(10)
vector[4]=1
print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [3]:
# 2. Create a vector with values ranging from 10 to 49.

arr = np.arange(10,50)
print("Values Ranging from 10 to 49" ,arr)

Values Ranging from 10 to 49 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [4]:
# 3. Create a 3x3 matrix with values ranging from 0 to 8

matrix = np.arange(9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [16]:
# 4. Find indices of non-zero elements from [1,2,0,0,4,0]

elements = np.array([1,2,0,0,47,0])
result = np.where(elements != 0)[0]
print("Indices of non-zero Elements are ",result)

Indices of non-zero Elements are  [0 1 4]


In [19]:
# 5. Create a 10x10 array with random values and find the minimum and maximum values.

arr = np.random.randint(100,size=(10,10))
print(arr)
min = np.min(arr)
max = np.max(arr)
print("Min = ",min)
print("Max = ",max)

[[39 92 54 84 45 72 51  3 86 68]
 [70 80 27  1 25 22 23 58 67 94]
 [95 35 35 90  3 67 75  7 82 35]
 [73 71 19 40 45 41 96 56 66 64]
 [68 93 84 28 40 64 55 19 72 66]
 [22 15 68 45 46 19 67 14 63 94]
 [39 16 96 50 82 24 60 25 93 22]
 [93 40 26 70 56 82 99 90 36 56]
 [58 67 45 16 78 49 40 54 86 56]
 [21 60 96 45 55 15  4 85 58 99]]
Min =  1
Max =  99


In [22]:
# 6. Create a random vector of size 30 and find the mean value.

vector = np.random.randint(100,size=(10,3))
result = vector.mean()
print(vector)
print("Mean Value = ",result)

[[89 89 91]
 [66 12  3]
 [43 51 74]
 [52 59 68]
 [84  8 93]
 [75 99 63]
 [15 10 11]
 [83 20 47]
 [91 67 38]
 [74 77 35]]
Mean Value =  56.233333333333334
